### ISSUE TITLE
Getting a jinja2.exceptions.TemplateNotFound exceptions while generating directory setup for new visualization

### ISSUE THREAD

**Issue by swapatGithub** [pixiedust/pixiedust#697]
As a Data Engineer, I want to create my own visualization and use it in pixiedust class 

### Expected behavior
After entering the command 'jupyter pixiedust generate' in shell, a project directory should get created on the server which I should be able to install and use it in the code.

### Actual behavior
(my_env)[usr@10p newVizD3]$ jupyter pixiedust generate
Step 1: Please enter the name of your project: sampleViz
Step 2: Directory for your project: /home/usr/pixie/newVizD3
        Keep y/n [y]? y
Step 3: [Optional] Please enter the project author: 
Step 4: [Optional] Please enter the project author email address: 
Step 5: [Optional] Please enter the project url: 
Step 6: Please enter the project type:
        1.Display Visualization
        2.Chart Renderer
Project type:1
Traceback (most recent call last):
  File "/users/usr/.conda/envs/my_env/bin/jupyter-pixiedust", line 11, in <module>
    sys.exit(main())
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/install/pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/install/pixiedustapp.py", line 38, in start
    return self.subapp.start()
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/install/generate.py", line 54, in start
    self.doStart()
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/install/generate.py", line 100, in doStart
    self.writeFile(["setup.pytpl","LICENSE.tpl","MANIFEST.intpl","readme.mdtpl","setup.cfgtpl"])
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/install/generate.py", line 118, in writeFile
    f.write(PixiedustGenerate.env.get_template(template).render(this=self).encode("utf-8","ignore"))
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/users/usr/.conda/envs/my_env/lib/python3.4/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: setup.pytpl

### Steps to reproduce the behavior
below are the package versions I am using,
pixiedust - 1.1.11
Jinja2 - 2.10

Thanks and Regards,
Swapnil

**Comment by DTAIEB** [comment]
Fix provided in PR #699
