### ISSUE TITLE
Issue when  working with S3 data sources

### ISSUE THREAD

**Issue by jmbertoncelli** [pixiedust/pixiedust#701]
All the logic works but the progress monitor doesn't like working with an S3 source... 

Code:

sc._jsc.hadoopConfiguration().set("fs.s3a.awsAccessKeyId", aws_access_key_id)
sc._jsc.hadoopConfiguration().set("fs.s3a.awsSecretAccessKey", aws_secret_access_key)
sc._jsc.hadoopConfiguration().set("fs.s3a.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
myRDD = sc.textFile("s3a://data-science-in-a-box/top/fake_customers_00100.csv")
myRDD.count()

Exception: 

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/root/miniconda2/envs/snake27/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/miniconda2/envs/snake27/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 47, in startSparkJobProgressMonitor
    progressMonitor = SparkJobProgressMonitor()
  File "/root/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 174, in __init__
    self.addSparkListener()
  File "/root/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 203, in addSparkListener
    _env.getTemplate("sparkJobProgressMonitor/addSparkListener.scala").render()
  File "/root/miniconda2/envs/snake27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2117, in run_cell_magic
    result = fn(magic_arg_s, cell)
  File "<decorator-gen-159>", line 2, in scala
  File "/root/miniconda2/envs/snake27/lib/python2.7/site-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/root/.local/lib/python2.7/site-packages/pixiedust/utils/scalaBridge.py", line 194, in scala
    runnerObject.callMethod("set" + key[0].upper() + key[1:], val["initValue"])
  File "/root/.local/lib/python2.7/site-packages/pixiedust/utils/javaBridge.py", line 154, in callMethod
    raise ValueError("Method {0} that matches the given arguments not found".format(methodName) )
ValueError: Method setMyRDD that matches the given arguments not found

**Comment by DTAIEB** [comment]
@jmbertoncelli Which version of Spark?

**Comment by jmbertoncelli** [comment]
the most recent 2.3.0

**Comment by jmbertoncelli** [comment]
Hello

I was able to run Pixiedust with all the latest Spark versions (from 2.0.0).  I just make sure that Java, Scala and Spark are all in sync.  After that just get Pixiedust using python pip then follow the documentation.  If you are just using Spark local or standalone cluster then check the Jupyter kernel and adjust the parameters.

By the way my post about S3 and Pixiedust it is only the feedback progress bar widget that does not work… everything else does work including reading / writing on S3.
JM

**Comment by jmbertoncelli** [comment]
![image](https://user-images.githubusercontent.com/9658723/45965561-69072e00-bfee-11e8-9191-b182bad46dd0.png)
