### ISSUE TITLE
When run pixiedust.sampleData(6), there is error "Py4JJavaErrorTraceback (most recent call last)"

### ISSUE THREAD

**Issue by hineli** [pixiedust/pixiedust#703]
When I run "df3 = pixiedust.sampleData()",  the jupyter notebook is working fine with the correct display.
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/30453092/43825493-7e0fb88a-9b27-11e8-9cb6-35a1e68639d4.png">

But when I run "df = pixiedust.sampleData(6)", it returns the error:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/30453092/43825590-bd5ab29c-9b27-11e8-8391-a1ff3834f0d3.png">

Could you help me to understand why this happen? And how to resolve it?

**Comment by vabarbosa** [comment]
@hineli are you still reproducing the issue?
if you run the following commands in separate cells what are the outputs?

```python
sc
```

```python
!pip show pixiedust
```

```python
import sys
sys.version
```

in addition, are you successfully able to run?
```python
df = pixiedust.sampleData(6, forcePandas=True)
```

are you successful with other `sampleData`?
```python
df = pixiedust.sampleData(1)
```

lastly, can you provide the entire stack trace?

**Comment by vabarbosa** [comment]
From https://dataplatform.cloud.ibm.com/docs/content/analyze-data/spark-envs.html:

> You can't access files in the temporary file system of a Spark cluster in a Spark environment because /tmp isn't a shared file system and can't be accessed by the Spark executors.

**Comment by roee88** [comment]
This still happens when IAE is used

```
Creating pySpark DataFrame for 'Million dollar home sales in Massachusetts, USA Feb 2017 through Jan 2018'. Please wait...
Loading file using 'SparkSession'
Successfully created pySpark DataFrame for 'Million dollar home sales in Massachusetts, USA Feb 2017 through Jan 2018'
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:

Py4JJavaError: An error occurred while calling o434.load.
: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://chs-nks-729-mn002.us-south.ae.appdomain.cloud:8020/tmp/tmp0l9z0orw;
	at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:715)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:388)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)


During handling of the above exception, another exception occurred:

AnalysisException                         Traceback (most recent call last)
<ipython-input-18-858f35643dff> in <module>()
----> 1 pixiedust.sampleData(6)

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/environment.py in wrapper(*args, **kwargs)
    104             kwargs.pop("fromScala")
    105             fromScala = True
--> 106         retValue = func(*args, **kwargs)
    107         if fromScala and retValue is not None:
    108             from pixiedust.utils.javaBridge import JavaWrapper

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/sampleData.py in sampleData(dataId, type, forcePandas)
     85 def sampleData(dataId=None, type='csv', forcePandas=False):
     86     global dataDefs
---> 87     return SampleData(dataDefs, forcePandas).sampleData(dataId, type)
     88 
     89 class SampleData(object):

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/sampleData.py in sampleData(self, dataId, type)
     98             self.printSampleDataList()
     99         elif str(dataId) in dataDefs:
--> 100             return self.loadSparkDataFrameFromSampleData(dataDefs[str(dataId)])
    101         elif "https://" in str(dataId) or "http://" in str(dataId) or "file://" in str(dataId):
    102             if type is 'json':

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/sampleData.py in loadSparkDataFrameFromSampleData(self, dataDef)
    189 
    190     def loadSparkDataFrameFromSampleData(self, dataDef):
--> 191         return Downloader(dataDef, self.forcePandas).download(self.dataLoader)
    192 
    193     def loadSparkDataFrameFromUrl(self, dataUrl):

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/sampleData.py in download(self, dataLoader)
    264                 print("Creating {1} DataFrame for '{0}'. Please wait...".\
    265                     format(displayName, 'pySpark' if Environment.hasSpark and not self.forcePandas else 'pandas'))
--> 266                 return dataLoader(path, self.dataDef.get("schema", None))
    267             finally:
    268                 print("Successfully created {1} DataFrame for '{0}'".\

/home/wce/clsadmin/pipAnaconda3Packages/pixiedust/utils/sampleData.py in dataLoader(self, path, schema)
    141                     return csvload.schema(StructType([StructField(item[0], getType(item[1]), True) for item in schema])).load(path)
    142                 else:
--> 143                     return csvload.option("inferSchema", "true").load(path)
    144         else:
    145             print("Loading file using 'pandas'")

/usr/hdp/current/spark2-client/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:

/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py in deco(*a, **kw)
     67                                              e.java_exception.getStackTrace()))
     68             if s.startswith('org.apache.spark.sql.AnalysisException: '):
---> 69                 raise AnalysisException(s.split(': ', 1)[1], stackTrace)
     70             if s.startswith('org.apache.spark.sql.catalyst.analysis'):
     71                 raise AnalysisException(s.split(': ', 1)[1], stackTrace)

AnalysisException: 'Path does not exist: hdfs://chs-nks-729-mn002.us-south.ae.appdomain.cloud:8020/tmp/tmp0l9z0orw;'

```
