### ISSUE TITLE
Not working in Jupyter Lab

### ISSUE THREAD

**Issue by btlvr** [pixiedust/pixiedust#711]
### Expected behavior
`import pixiedust` should work

### Actual behavior
```
import pixiedust
```
```
Pixiedust database opened successfully
Pixiedust version 1.1.11
```
```
Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-730caec4e245>", line 1, in <module>
    import pixiedust

  File "/usr/lib/python3.7/site-packages/pixiedust/__init__.py", line 59, in <module>
    from pixiedust.display import display

  File "/usr/lib/python3.7/site-packages/pixiedust/display/__init__.py", line 20, in <module>
    from pixiedust.utils.astParse import get_caller_text

  File "/usr/lib/python3.7/site-packages/pixiedust/utils/astParse.py", line 19, in <module>
    from astunparse import unparse

  File "/usr/lib/python3.7/site-packages/astunparse/__init__.py", line 4, in <module>
    from .unparser import Unparser

  File "/usr/lib/python3.7/site-packages/astunparse/unparser.py", line 331
    def _generic_FunctionDef(self, t, async=False):
                                          ^
SyntaxError: invalid syntax
```
### Other
I installed pixie and Jupyter with pip. I'm using Arch.

**Comment by fperez** [comment]
This seems like a duplicate of #613... Perhaps we can close this one and focus the JupyterLab status there?

**Comment by Uldiniad** [comment]
https://github.com/simonpercivall/astunparse/issues/26
