### ISSUE TITLE
Py4JJavaErrorTraceback  while using pixiedust in a jupyter notebook(studio)

### ISSUE THREAD

**Issue by VidyasagarMSC** [pixiedust/pixiedust#721]
!pip install --upgrade pixiedust
import pixiedust
 Use play-json version 2.5.9. Latest version is not supported at this time.
pixiedust.installPackage("com.typesafe.play:play-json_2.11:2.5.9")
Get the latest sql-cloudant library
pixiedust.installPackage("org.apache.bahir:spark-sql-cloudant_2.11:0")

cloudantdata=sqlContext.read.format("org.apache.bahir.cloudant").\
option("cloudant.host", host).\
option("cloudant.username", username).\
option("cloudant.password", password).\
option("view","_design/iotp/_view/by-date").\
option("jsonstore.rdd.partitions", 4).\
load(dbName)

**Error**

Py4JJavaErrorTraceback (most recent call last)
<ipython-input-6-735ab4a9dea7> in <module>()
----> 1 cloudantdata=sqlContext.read.format("org.apache.bahir.cloudant").option("cloudant.host", host).option("cloudant.username", username).option("cloudant.password", password).option("view","_design/iotp/_view/by-date").option("jsonstore.rdd.partitions", 4).load(dbName)

/usr/local/src/spark21master/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    147         self.options(**options)
    148         if isinstance(path, basestring):
--> 149             return self._df(self._jreader.load(path))
    150         elif path is not None:
    151             if type(path) != list:

/usr/local/src/spark21master/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/usr/local/src/spark21master/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/src/spark21master/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o96.load.
: java.lang.NoSuchMethodError: org/apache/spark/sql/DataFrameReader.json(Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/Dataset; (loaded from file:/usr/local/src/spark21master/spark-2.1.2-bin-2.7.3/jars/spark-sql_2.11-2.1.2.jar by sun.misc.Launcher$AppClassLoader@36dc2fb) called from class org.apache.bahir.cloudant.DefaultSource (loaded from file:/gpfs/global_fs01/sym_shared/YPProdSpark/user/s82f-d9b8203020ee76-eeb5266277e2/data/libs/spark-sql-cloudant_2.11-2.2.1.jar by sun.misc.Launcher$AppClassLoader@36dc2fb).
	at org.apache.bahir.cloudant.DefaultSource.create(DefaultSource.scala:124)
	at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:95)
	at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:87)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:811)

**Comment by VidyasagarMSC** [comment]
Found a workaround and its here - https://github.com/IBM-Cloud/iot-device-phone-simulator/issues/2
