### ISSUE TITLE
Error in running Pixiedust with existing Spark Installation 

### ISSUE THREAD

**Issue by ganesh3** [pixiedust/pixiedust#723]
As a `<user type>`, I want to `<task>` so that `<goal>` (make this the title)

### Expected behavior
Pixiedust installation

### Actual behavior
(base) C:\WINDOWS\system32>jupyter pixiedust install
[32;1mStep 1: PIXIEDUST_HOME: C:\Users\ganes\pixiedust[0m
        Keep y/n [y]? n
[32;1mPlease enter a PIXIEDUST_HOME location: [0mD:\Pixiedust\
[32;1mStep 2: SPARK_HOME: D:\Pixiedust\bin\spark[0m
        Keep y/n [y]? y
Select an existing spark install or create a new one
[32;1m1. spark-2.3.1-bin-hadoop2.7
2. Create a new spark Install[0m
        Enter your selection: 1
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\jupyter-pixiedust.EXE\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\install\pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "d:\anaconda3\lib\site-packages\install\createKernel.py", line 154, in parse_command_line
    spark_version = self.get_spark_version()
  File "d:\anaconda3\lib\site-packages\install\createKernel.py", line 379, in get_spark_version
    pyspark_out = subprocess.check_output([pyspark, "--version"], stderr=subprocess.STDOUT).decode("utf-8")
  File "d:\anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "d:\anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "d:\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "d:\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

### Steps to reproduce the behavior
Steps as depicted in READ.ME file

**Comment by accedomesa** [comment]
The error is in subprocess.check_output line, it seems to be using the linux binary with the same name.
Temporary changing `C:\bin\Anaconda3\Lib\site-packages\install\createKernel.py` let me advance the installation a few steps (it errored due to being unable to download the spark cloudant connector and then failed with 'PixiedustInstall' object has no attribute 'sparkCloudantPath')

Add the correct file extension in the lines 378 and 417
```
old: pyspark = "{}{}bin{}pyspark".format(self.spark_home, os.sep, os.sep)
new: pyspark = "{}{}bin{}pyspark.cmd".format(self.spark_home, os.sep, os.sep)
old: scala = os.path.join(dir, "bin", "scala")
new: scala = os.path.join(dir, "bin", "scala.bat")
```

**Comment by ganesh3** [comment]
Made the changes but still getting an error

(base) C:\WINDOWS\system32>jupyter pixiedust install
[32;1mStep 1: PIXIEDUST_HOME: C:\Users\ganes\pixiedust[0m
        Keep y/n [y]? n
[32;1mPlease enter a PIXIEDUST_HOME location: [0mD:\Pixiedust
[32;1mStep 2: SPARK_HOME: D:\Pixiedust\bin\spark[0m
        Keep y/n [y]? y
Select an existing spark install or create a new one
[32;1m1. spark-2.3.1-bin-hadoop2.7
2. Create a new spark Install[0m
        Enter your selection: 2
[32;1mWhat version would you like to download? 1.6.3, 2.0.2, 2.1.0, 2.2.0, 2.3.0 [2.3.0]: [0m2.2.0
SPARK_HOME will be set to D:\Pixiedust\bin\spark\spark-2.2.0-bin-hadoop2.7
Downloading Spark 2.2.0
 0 %
[F 1 %
[F 1 %
[F 2 %
[F 2 %
[F 3 %
[F 3 %
[F 4 %
[F 4 %
[F 5 %
[F 5 %
[F 6 %
[F 6 %
[F 7 %
[F 7 %
[F 8 %
[F 8 %
[F 9 %
[F 9 %
[F 10 %
[F 10 %
[F 11 %
[F 11 %
[F 12 %
[F 12 %
[F 13 %
[F 13 %
[F 14 %
[F 14 %
[F 15 %
[F 15 %
[F 16 %
[F 16 %
[F 17 %
[F 18 %
[F 18 %
[F 19 %
[F 19 %
[F 20 %
[F 20 %
[F 21 %
[F 21 %
[F 22 %
[F 22 %
[F 23 %
[F 23 %
[F 24 %
[F 24 %
[F 25 %
[F 25 %
[F 26 %
[F 26 %
[F 27 %
[F 27 %
[F 28 %
[F 28 %
[F 29 %
[F 29 %
[F 30 %
[F 30 %
[F 31 %
[F 31 %
[F 32 %
[F 32 %
[F 33 %
[F 33 %
[F 34 %
[F 34 %
[F 35 %
[F 36 %
[F 36 %
[F 37 %
[F 37 %
[F 38 %
[F 38 %
[F 39 %
[F 39 %
[F 40 %
[F 40 %
[F 41 %
[F 41 %
[F 42 %
[F 42 %
[F 43 %
[F 43 %
[F 44 %
[F 44 %
[F 45 %
[F 45 %
[F 46 %
[F 46 %
[F 47 %
[F 47 %
[F 48 %
[F 48 %
[F 49 %
[F 49 %
[F 50 %
[F 50 %
[F 51 %
[F 51 %
[F 52 %
[F 53 %
[F 53 %
[F 54 %
[F 54 %
[F 55 %
[F 55 %
[F 56 %
[F 56 %
[F 57 %
[F 57 %
[F 58 %
[F 58 %
[F 59 %
[F 59 %
[F 60 %
[F 60 %
[F 61 %
[F 61 %
[F 62 %
[F 62 %
[F 63 %
[F 63 %
[F 64 %
[F 64 %
[F 65 %
[F 65 %
[F 66 %
[F 66 %
[F 67 %
[F 67 %
[F 68 %
[F 68 %
[F 69 %
[F 69 %
[F 70 %
[F 71 %
[F 71 %
[F 72 %
[F 72 %
[F 73 %
[F 73 %
[F 74 %
[F 74 %
[F 75 %
[F 75 %
[F 76 %
[F 76 %
[F 77 %
[F 77 %
[F 78 %
[F 78 %
[F 79 %
[F 79 %
[F 80 %
[F 80 %
[F 81 %
[F 81 %
[F 82 %
[F 82 %
[F 83 %
[F 83 %
[F 84 %
[F 84 %
[F 85 %
[F 85 %
[F 86 %
[F 86 %
[F 87 %
[F 88 %
[F 88 %
[F 89 %
[F 89 %
[F 90 %
[F 90 %
[F 91 %
[F 91 %
[F 92 %
[F 92 %
[F 93 %
[F 93 %
[F 94 %
[F 94 %
[F 95 %
[F 95 %
[F 96 %
[F 96 %
[F 97 %
[F 97 %
[F 98 %
[F 98 %
[F 99 %
[F 99 %
[F 100 %
[F
[FExtracting Spark 2.2.0 to D:\Pixiedust\bin\spark
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\jupyter-pixiedust.EXE\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\install\pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "d:\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\anaconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "d:\anaconda3\lib\site-packages\install\createKernel.py", line 151, in parse_command_line
    self.download_spark(silent, silent_spark_version)
  File "d:\anaconda3\lib\site-packages\install\createKernel.py", line 410, in download_spark
    self.extract_temp_file(temp_file, self.spark_home)
  File "d:\anaconda3\lib\site-packages\install\createKernel.py", line 479, in extract_temp_file
    tar = tarfile.open(temp_file.name, "r:gz")
  File "d:\anaconda3\lib\tarfile.py", line 1587, in open
    return func(name, filemode, fileobj, **kwargs)
  File "d:\anaconda3\lib\tarfile.py", line 1634, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "d:\anaconda3\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ganes\\AppData\\Local\\Temp\\tmpkvov6cwf.tgz'
