### ISSUE TITLE
AttributeError: 'PixiedustInstall' object has no attribute 'sparkCloudantPath'

### ISSUE THREAD

**Issue by bhaskar-manguluri** [pixiedust/pixiedust#753]
As a jupyter user, I want to install pixiediust so that I can use pixiedust in jupyter

### Expected behavior
during jupyter pixiedust install 
step 4: Kernel Name: Python-with-Pixiedust_Spark-version
	Keep y/n [y]? y
I should have env saved

### Actual behavior
File "/Users/bhaskar/work/anon/env/bin/jupyter-pixiedust", line 11, in <module>
    sys.exit(main())
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/install/pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/jupyter_core/application.py", line 238, in initialize
    self.parse_command_line(argv)
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/install/createKernel.py", line 279, in parse_command_line
    dest = self.createKernelSpec()
  File "/Users/bhaskar/work/anon/env/lib/python3.5/site-packages/install/createKernel.py", line 514, in createKernelSpec
    self.sparkCloudantPath,
AttributeError: 'PixiedustInstall' object has no attribute 'sparkCloudantPath'

### Steps to reproduce the behavior
install java on mac os 10.14.2, by **brew cask install java8**
create python3.5 virtualenv using **virtualenv -p python3.5 env**
activate the environment **source env/bin/activate**
install jupyter from pypi  **pip install jupyter**
install pixiedust from pypi using **pip install pixiedust**
install pixiedust to use in jupyter kernel by **jupyter pixiedust install**
--select locations and versions for dependencies--scala and spark
--in step4 when prompted to save kernel with name (y/N) select y

**Comment by JunyongYao** [comment]
@bhaskar-manguluri  
I met the same issue and it disappeared after I rerun  `jupyter pixiedust install`

**Comment by memory-yancy** [comment]
Check similar directory `/root/pixiedust/bin/` exist or not see output info? For me,  `pixiedust` will download `cloudant-spark-v2.0.0-185.jar` to `/root/pixiedust/bin/cloudant-spark-v2.0.0-185.jar`, but directory `/root/pixiedust/bin/` doesn't exist. So, I create it and run again :

```
root@localhost:~# jupyter-pixiedust install --silent
Error downloading Cloudant Jar: [Errno 2] No such file or directory: '/root/pixiedust/bin/cloudant-spark-v2.0.0-185.jar'. Install will continue without the spark Cloudant connector
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-pixiedust", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/install/pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
... ...
```

```
root@localhost:~# mkdir -p /root/pixiedust/bin/
# avoid interactive Yes or No inputting
# jdk tarball, scala tarball, spark tarball downloaded to /root
root@localhost:~# export SCALA_HOME=/root/scala-2.13.0
root@localhost:~# export SPARK_HOME=/root/spark-2.4.0-bin-hadoop2.7
root@localhost:~# export JAVA_HOME=/root/jdk-9/

root@localhost:~# jupyter-pixiedust install --silent
downloaded spark cloudant jar: /root/pixiedust/bin/cloudant-spark-v2.0.0-185.jar
self.kernelInternalName pythonwithpixiedustspark24
[PixiedustInstall] Installed kernelspec pythonwithpixiedustspark24 in /root/.local/share/jupyter/kernels/pythonwithpixiedustspark24
Downloading intro notebooks into /root/pixiedust/notebooks
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 1 - Easy Visualizations.ipynb : done
... ...

```


You can change `cloudant-spark-v2.0.0-185.jar` location by setting `export PIXIEDUST_HOME=/your/custom/dir`(default value is `~`). If so, remember to create target directory.
